---
- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: Export the master node config
      shell: >
        set -o errexit; \
        kubectl -n kube-public get configmap cluster-info -o jsonpath='{.data.kubeconfig}' > discovery.yaml"
      args:
        chdir: $HOME

- hosts: all
  become: yes
  tasks:
    - name: Fetch discovery.yaml from the master node to ansible VM
      run_once: yes
      fetch: src=/home/ubuntu/discovery.yaml dest=/root flat=yes
      when: "{{ inventory_hostname == 'k8s-c2-master01' }}"

    - name: Copy the file from Ansible VM to workers
      copy: src=/root/discovery.yaml dest=/home/ubuntu
      when: "{{ inventory_hostname == 'k8s-c2-worker01' }}"

- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: kubeadm join --config /etc/kubernetes/kubeadminitworker.yaml
      args:
        chdir: $HOME


- name: Install Tetration agents on K8s worker nodes
  hosts: workers
  tasks:
    - name: perform apt-get update and update the cache
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
 
    - name: install linux packages
      become: yes
      apt:
        name: ['rpm', 'lsb-release', 'ipset', 'dmidecode', 'gawk', 'util-linux', 'curl', 'openssl', 'sed', 'alien']
        state: present

    - name: Download Cisco Tetration Enforcer agent
      become: yes
      get_url:
        url: http://192.168.20.100/tet-sensor-3.3.2.2-1.u18-tet.enforcer.x86_64.rpm
        dest: /opt
        mode: 0755
        #group: admin
        #owner: admin

    - name: Run alien to convert rpm to debian package
      become: yes
      shell: alien /opt/tet-sensor-3.3.2.2-1.u18-tet.enforcer.x86_64.rpm --scripts
      args:
        chdir: /opt

    - name: Install converted tetration debian package
      become: yes
      apt:
        deb: /opt/tet-sensor-site_3.3.2.2-2_amd64.deb